"""API Integration Gateway Models (Phase 15.9).

Defines immutable Pydantic v2 domain models and enums for the provider-independent
API Integration Gateway Runtime, including pipeline stages, integration requests,
responses, request/response contexts, capabilities, health, statistics, and diagnostics.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, Optional, Tuple

# pyrefly: ignore [missing-import]
from pydantic import BaseModel, ConfigDict, Field


class PipelineStage(str, Enum):
    """Execution stages for the API Integration Gateway pipeline."""

    ROUTING = "ROUTING"
    MIDDLEWARE = "MIDDLEWARE"
    AUTHENTICATION = "AUTHENTICATION"
    VALIDATION = "VALIDATION"
    VERSIONING = "VERSIONING"
    PROTECTION = "PROTECTION"
    WEBSOCKET = "WEBSOCKET"
    COMPLETE = "COMPLETE"


class IntegrationRuntimeState(str, Enum):
    """Lifecycle states for the integration runtime."""

    UNINITIALIZED = "UNINITIALIZED"
    INITIALIZING = "INITIALIZING"
    READY = "READY"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"


class ApiPipelineStage(BaseModel):
    """Immutable definition of a gateway pipeline stage."""

    model_config = ConfigDict(frozen=True)

    stage_id: str
    stage: PipelineStage
    is_enabled: bool = True
    order: int = 0
    description: str = ""


class ApiIntegrationRequest(BaseModel):
    """Immutable representation of an incoming request entering the integration gateway."""

    model_config = ConfigDict(frozen=True)

    request_id: str
    path: str
    method: str = "GET"
    headers: Dict[str, str] = Field(default_factory=dict)
    params: Dict[str, Any] = Field(default_factory=dict)
    body: Optional[Any] = None
    received_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ApiIntegrationResponse(BaseModel):
    """Immutable representation of an outgoing response generated by the integration gateway."""

    model_config = ConfigDict(frozen=True)

    response_id: str
    request_id: str
    status_code: int = 200
    headers: Dict[str, str] = Field(default_factory=dict)
    body: Optional[Any] = None
    stage_reached: PipelineStage = PipelineStage.COMPLETE
    completed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ApiRequestContext(BaseModel):
    """Immutable request execution context tracking runtime state and pipeline progress."""

    model_config = ConfigDict(frozen=True)

    context_id: str
    request: ApiIntegrationRequest
    current_stage: PipelineStage = PipelineStage.ROUTING
    attributes: Dict[str, Any] = Field(default_factory=dict)


class ApiResponseContext(BaseModel):
    """Immutable response context encapsulating gateway execution metrics and diagnostics."""

    model_config = ConfigDict(frozen=True)

    context_id: str
    response: ApiIntegrationResponse
    execution_time_ms: float = 0.0
    diagnostics: Dict[str, Any] = Field(default_factory=dict)


class IntegrationCapabilities(BaseModel):
    """Immutable model declaring supported integration runtime capabilities."""

    model_config = ConfigDict(frozen=True)

    supports_gateway_orchestration: bool = True
    supports_request_coordination: bool = True
    supports_response_coordination: bool = True
    supports_stage_pipeline: bool = True
    custom_capabilities: Dict[str, bool] = Field(default_factory=dict)


class IntegrationStatistics(BaseModel):
    """Immutable aggregate metrics and statistics for the integration runtime."""

    model_config = ConfigDict(frozen=True)

    total_requests_processed: int = 0
    successful_requests: int = 0
    failed_requests: int = 0
    total_pipeline_executions: int = 0
    metrics: Dict[str, Any] = Field(default_factory=dict)


class IntegrationHealth(BaseModel):
    """Immutable health status evaluation of the integration runtime."""

    model_config = ConfigDict(frozen=True)

    is_healthy: bool = True
    state: IntegrationRuntimeState = IntegrationRuntimeState.UNINITIALIZED
    details: Dict[str, Any] = Field(default_factory=dict)
    issues: Tuple[str, ...] = Field(default_factory=tuple)
    checked_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class IntegrationDiagnostics(BaseModel):
    """Immutable diagnostic information for troubleshooting and telemetry."""

    model_config = ConfigDict(frozen=True)

    state: IntegrationRuntimeState = IntegrationRuntimeState.UNINITIALIZED
    active_gateways_count: int = 0
    processed_requests_count: int = 0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    thread_count: int = 0
    diagnostic_messages: Tuple[str, ...] = Field(default_factory=tuple)
    details: Dict[str, Any] = Field(default_factory=dict)
