"""Typed intent definitions for Auralis core orchestration."""

from __future__ import annotations

from enum import Enum


class Intent(str, Enum):
    """Supported assistant execution intents."""

    OPEN_FOLDER = "OPEN_FOLDER"
    OPEN_FILE = "OPEN_FILE"
    SEARCH_FILE = "SEARCH_FILE"
    LIST_DIRECTORY = "LIST_DIRECTORY"
    CREATE_FOLDER = "CREATE_FOLDER"
    DELETE_FOLDER = "DELETE_FOLDER"
    ORGANIZE_FOLDER = "ORGANIZE_FOLDER"
    GET_FILE_INFO = "GET_FILE_INFO"
    OPEN_APPLICATION = "OPEN_APPLICATION"
    CLOSE_APPLICATION = "CLOSE_APPLICATION"
    RESTART_APPLICATION = "RESTART_APPLICATION"
    LIST_RUNNING_APPLICATIONS = "LIST_RUNNING_APPLICATIONS"
    MINIMIZE_WINDOW = "MINIMIZE_WINDOW"
    MAXIMIZE_WINDOW = "MAXIMIZE_WINDOW"
    RESTORE_WINDOW = "RESTORE_WINDOW"
    FOCUS_WINDOW = "FOCUS_WINDOW"
    CLOSE_WINDOW = "CLOSE_WINDOW"
    SHOW_DESKTOP = "SHOW_DESKTOP"
    LIST_WINDOWS = "LIST_WINDOWS"
    UNKNOWN = "UNKNOWN"


__all__ = ["Intent"]