"""Typed intent definitions for Auralis core orchestration."""

from __future__ import annotations

from enum import Enum


class Intent(str, Enum):
    """Supported assistant execution intents."""

    OPEN_FOLDER = "OPEN_FOLDER"
    OPEN_FILE = "OPEN_FILE"
    SEARCH_FILE = "SEARCH_FILE"
    LIST_DIRECTORY = "LIST_DIRECTORY"
    CREATE_FOLDER = "CREATE_FOLDER"
    DELETE_FOLDER = "DELETE_FOLDER"
    ORGANIZE_FOLDER = "ORGANIZE_FOLDER"
    GET_FILE_INFO = "GET_FILE_INFO"
    OPEN_APPLICATION = "OPEN_APPLICATION"
    CLOSE_APPLICATION = "CLOSE_APPLICATION"
    RESTART_APPLICATION = "RESTART_APPLICATION"
    LIST_RUNNING_APPLICATIONS = "LIST_RUNNING_APPLICATIONS"
    MINIMIZE_WINDOW = "MINIMIZE_WINDOW"
    MAXIMIZE_WINDOW = "MAXIMIZE_WINDOW"
    RESTORE_WINDOW = "RESTORE_WINDOW"
    FOCUS_WINDOW = "FOCUS_WINDOW"
    CLOSE_WINDOW = "CLOSE_WINDOW"
    SHOW_DESKTOP = "SHOW_DESKTOP"
    LIST_WINDOWS = "LIST_WINDOWS"
    SET_VOLUME = "SET_VOLUME"
    MUTE = "MUTE"
    UNMUTE = "UNMUTE"
    SET_BRIGHTNESS = "SET_BRIGHTNESS"
    LOCK_PC = "LOCK_PC"
    SLEEP_PC = "SLEEP_PC"
    SHUTDOWN_PC = "SHUTDOWN_PC"
    RESTART_PC = "RESTART_PC"
    HIBERNATE_PC = "HIBERNATE_PC"
    ENABLE_WIFI = "ENABLE_WIFI"
    DISABLE_WIFI = "DISABLE_WIFI"
    ENABLE_BLUETOOTH = "ENABLE_BLUETOOTH"
    DISABLE_BLUETOOTH = "DISABLE_BLUETOOTH"
    COPY_SELECTION = "COPY_SELECTION"
    PASTE = "PASTE"
    CLEAR_CLIPBOARD = "CLEAR_CLIPBOARD"
    SHOW_CLIPBOARD = "SHOW_CLIPBOARD"
    SAVE_CLIPBOARD = "SAVE_CLIPBOARD"
    COPY_FILE_PATH = "COPY_FILE_PATH"
    UNKNOWN = "UNKNOWN"


__all__ = ["Intent"]