export const PluginState = {
  UNREGISTERED: 'UNREGISTERED',
  REGISTERED: 'REGISTERED',
  UNLOADED: 'UNLOADED',
  LOADING: 'LOADING',
  LOADED: 'LOADED',
  INITIALIZING: 'INITIALIZING',
  READY: 'READY',
  ACTIVE: 'ACTIVE',
  DEACTIVATING: 'DEACTIVATING',
  DEACTIVATED: 'DEACTIVATED',
  DISABLED: 'DISABLED',
  DISPOSING: 'DISPOSING',
  DISPOSED: 'DISPOSED',
  ERROR: 'ERROR',
  FAILED: 'FAILED',
} as const;

export type PluginStateValue = (typeof PluginState)[keyof typeof PluginState];
