"""
Module: backend.ai.models

Responsibility:
    Defines the shared data models and schemas used across the AI subsystem.
    Enforces typed communication between AI sub-modules.

This module SHOULD:
    - Define dataclasses representing chat records, LLM inputs, tool calls, and safety audits.
    - Provide structure schemas that are easy to serialize and deserialize.
    - Use strict Python type hints to enforce model parameters.

This module should NEVER:
    - Include networking, file writes, or API request execution logic.
    - Reference implementation databases or LLM provider SDK models.
    - Store hardcoded secrets or config values.
"""

from typing import Dict, Any, List, Optional
import time


class ChatMessage:
    """Represents a single conversational turn between the user and assistant."""
    
    def __init__(self, role: str, content: str, metadata: Optional[Dict[str, Any]] = None) -> None:
        self.role: str = role
        self.content: str = content
        self.timestamp: float = time.time()
        self.metadata: Dict[str, Any] = metadata or {}

    def to_dict(self) -> Dict[str, Any]:
        """Serializes the ChatMessage into a flat dictionary."""
        return {
            "role": self.role,
            "content": self.content,
            "timestamp": self.timestamp,
            "metadata": self.metadata
        }


class ToolDefinition:
    """Declares a system capability as a JSON-schema tool for LLM consumption."""
    
    def __init__(self, name: str, description: str, parameters: Dict[str, Any]) -> None:
        self.name: str = name
        self.description: str = description
        self.parameters: Dict[str, Any] = parameters


class PromptPayload:
    """Holds the complete compiled prompt context payload sent to LLM providers."""
    
    def __init__(self,
                 system_instructions: str,
                 messages: List[ChatMessage],
                 tools: List[ToolDefinition],
                 variables: Optional[Dict[str, Any]] = None) -> None:
        self.system_instructions: str = system_instructions
        self.messages: List[ChatMessage] = messages
        self.tools: List[ToolDefinition] = tools
        self.variables: Dict[str, Any] = variables or {}


class ToolCallRequest:
    """Represents a tool invocation request generated by the LLM."""
    
    def __init__(self, call_id: str, capability: str, action: str, arguments: Dict[str, Any]) -> None:
        self.call_id: str = call_id
        self.capability: str = capability
        self.action: str = action
        self.arguments: Dict[str, Any] = arguments


class ModelResponse:
    """Holds the structured response returned by an LLM provider engine."""
    
    def __init__(self,
                 content: str,
                 tool_calls: Optional[List[ToolCallRequest]] = None,
                 usage_stats: Optional[Dict[str, Any]] = None) -> None:
        self.content: str = content
        self.tool_calls: List[ToolCallRequest] = tool_calls or []
        self.usage_stats: Dict[str, Any] = usage_stats or {}


class SafetyReport:
    """Represents the safety audit report assessing execution risks of an LLM response."""
    
    def __init__(self, is_safe: bool, risk_score: float, blocked_reason: Optional[str] = None) -> None:
        self.is_safe: bool = is_safe
        self.risk_score: float = risk_score
        self.blocked_reason: Optional[str] = blocked_reason
