"""Configuration Package Exports (Phase 14.3.5).

Package exports for models, exceptions, interfaces, configuration sources,
source registry, source manager, schema manager, resolver, validator, profile manager, feature flag manager, secret store, secret manager, provider, runtime, and lazy singleton accessors.
"""

from backend.application.config.configuration_provider import ConfigurationProvider
from backend.application.config.configuration_resolver import ConfigurationResolver
from backend.application.config.configuration_runtime import ConfigurationRuntime
from backend.application.config.configuration_schema import ConfigurationSchemaManager
from backend.application.config.configuration_source_manager import ConfigurationSourceManager
from backend.application.config.configuration_validator import ConfigurationValidator
from backend.application.config.dotenv_source import DotEnvConfigurationSource
from backend.application.config.environment_source import EnvironmentConfigurationSource
from backend.application.config.exceptions import (
    ConfigurationException,
    ConfigurationInitializationError,
    ConfigurationProfileError,
    ConfigurationProviderError,
    ConfigurationSourceError,
    ConfigurationValidationError,
)
from backend.application.config.feature_flag_manager import FeatureFlagManager
from backend.application.config.interfaces import (
    IConfigurationDiagnostics,
    IConfigurationManager,
    IConfigurationProvider,
    IConfigurationRuntime,
    IConfigurationSource,
    IConfigurationValidator,
)
from backend.application.config.memory_source import MemoryConfigurationSource
from backend.application.config.models import (
    ConfigurationCapabilities,
    ConfigurationConstraint,
    ConfigurationContext,
    ConfigurationDefinition,
    ConfigurationDiagnostics,
    ConfigurationEntry,
    ConfigurationError,
    ConfigurationHealth,
    ConfigurationProfile,
    ConfigurationProfileDefinition,
    ConfigurationProfileSnapshot,
    ConfigurationProfileType,
    ConfigurationResolutionResult,
    ConfigurationRuntimeState,
    ConfigurationSchema,
    ConfigurationSnapshot,
    ConfigurationSource,
    ConfigurationSourceType,
    ConfigurationState,
    ConfigurationStatistics,
    ConfigurationValidationResult,
    ConfigurationWarning,
    FeatureEvaluation,
    FeatureFlag,
    FeatureHealth,
    FeatureStatistics,
    ProfileHealth,
    ProfileStatistics,
    ResolutionStatistics,
    SecretAccessRecord,
    SecretDefinition,
    SecretEntry,
    SecretHealth,
    SecretPolicy,
    SecretReference,
    SecretSnapshot,
    SecretStatistics,
    SecretType,
    SourceHealth,
    SourcePriority,
    SourceRegistration,
    SourceStatistics,
    ValidationStatistics,
)
from backend.application.config.profile_manager import ProfileManager
from backend.application.config.runtime import (
    get_configuration_provider,
    get_configuration_runtime,
    reset_configuration_provider,
    reset_configuration_runtime,
    set_configuration_provider,
    set_configuration_runtime,
)
from backend.application.config.secret_manager import SecretManager
from backend.application.config.secret_store import SecretStore
from backend.application.config.source_registry import SourceRegistry

__all__ = [
    "ConfigurationRuntimeState",
    "ConfigurationSourceType",
    "ConfigurationProfileType",
    "SecretType",
    "SourcePriority",
    "ConfigurationState",
    "ConfigurationCapabilities",
    "ConfigurationHealth",
    "ConfigurationStatistics",
    "ResolutionStatistics",
    "ValidationStatistics",
    "ProfileStatistics",
    "ProfileHealth",
    "FeatureStatistics",
    "FeatureHealth",
    "SecretStatistics",
    "SecretHealth",
    "SecretPolicy",
    "SecretDefinition",
    "SecretReference",
    "SecretEntry",
    "SecretSnapshot",
    "SecretAccessRecord",
    "ConfigurationContext",
    "ConfigurationProfile",
    "ConfigurationProfileDefinition",
    "ConfigurationProfileSnapshot",
    "FeatureFlag",
    "FeatureEvaluation",
    "ConfigurationSource",
    "SourceRegistration",
    "SourceStatistics",
    "SourceHealth",
    "ConfigurationEntry",
    "ConfigurationSnapshot",
    "ConfigurationError",
    "ConfigurationWarning",
    "ConfigurationConstraint",
    "ConfigurationDefinition",
    "ConfigurationSchema",
    "ConfigurationValidationResult",
    "ConfigurationResolutionResult",
    "ConfigurationDiagnostics",
    "ConfigurationException",
    "ConfigurationInitializationError",
    "ConfigurationValidationError",
    "ConfigurationProviderError",
    "ConfigurationProfileError",
    "ConfigurationSourceError",
    "IConfigurationSource",
    "IConfigurationDiagnostics",
    "IConfigurationValidator",
    "IConfigurationManager",
    "IConfigurationProvider",
    "IConfigurationRuntime",
    "MemoryConfigurationSource",
    "EnvironmentConfigurationSource",
    "DotEnvConfigurationSource",
    "SourceRegistry",
    "ConfigurationSchemaManager",
    "ConfigurationResolver",
    "ConfigurationValidator",
    "ProfileManager",
    "FeatureFlagManager",
    "SecretStore",
    "SecretManager",
    "ConfigurationSourceManager",
    "ConfigurationProvider",
    "ConfigurationRuntime",
    "get_configuration_runtime",
    "set_configuration_runtime",
    "reset_configuration_runtime",
    "get_configuration_provider",
    "set_configuration_provider",
    "reset_configuration_provider",
]
