"""Proactive Assistant & Notification Data Models for Auralis (Phase 13.8).

Defines immutable Pydantic v2 domain models and enums representing proactive events,
suggestions, recommendations, notifications, contexts, rules, evaluations, capabilities,
statistics, and health status using ConfigDict(frozen=True).
"""

from datetime import datetime, timezone
from enum import Enum
import uuid
from typing import Any, Dict, List, Optional
# pyrefly: ignore [missing-import]
from pydantic import BaseModel, ConfigDict, Field


class SuggestionPriority(str, Enum):
    """Priority weights assigned to proactive recommendations and notifications."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    MANDATORY = "MANDATORY"


class SuggestionType(str, Enum):
    """Categories of proactive suggestions."""

    RECOMMENDATION = "RECOMMENDATION"
    REMINDER = "REMINDER"
    CLARIFICATION = "CLARIFICATION"
    ACTION_SUGGESTION = "ACTION_SUGGESTION"
    SYSTEM_ALERT = "SYSTEM_ALERT"


class NotificationType(str, Enum):
    """Categories of assistant-level notifications."""

    INFO = "INFO"
    WARNING = "WARNING"
    RECOMMENDATION = "RECOMMENDATION"
    ACTION_REQUIRED = "ACTION_REQUIRED"


class ProactiveState(str, Enum):
    """Operational state of the proactive behavior engine."""

    IDLE = "IDLE"
    EVALUATING = "EVALUATING"
    READY = "READY"
    COOLDOWN = "COOLDOWN"
    DISABLED = "DISABLED"


class EvaluationResult(str, Enum):
    """Outcomes of rule evaluation."""

    TRIGGERED = "TRIGGERED"
    SUPPRESSED = "SUPPRESSED"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    NO_ACTION = "NO_ACTION"
    REJECTED = "REJECTED"


class ProactiveEvent(BaseModel):
    """Immutable event payload ingested by the proactive engine."""

    model_config = ConfigDict(frozen=True)

    event_id: str = Field(default_factory=lambda: f"pevt-{uuid.uuid4().hex[:8]}")
    event_type: str = "GENERIC_EVENT"
    source: str = "AssistantRuntime"
    payload: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ProactiveSuggestion(BaseModel):
    """Immutable suggestion item generated by recommendation rules."""

    model_config = ConfigDict(frozen=True)

    suggestion_id: str = Field(default_factory=lambda: f"sug-{uuid.uuid4().hex[:8]}")
    title: str = ""
    description: str = ""
    suggestion_type: SuggestionType = SuggestionType.RECOMMENDATION
    priority: SuggestionPriority = SuggestionPriority.MEDIUM
    score: float = Field(default=1.0, ge=0.0, le=1.0)
    action_key: Optional[str] = None
    payload: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ProactiveRecommendation(BaseModel):
    """Immutable detailed recommendation container."""

    model_config = ConfigDict(frozen=True)

    recommendation_id: str = Field(default_factory=lambda: f"rec-{uuid.uuid4().hex[:8]}")
    suggestion: ProactiveSuggestion = Field(default_factory=ProactiveSuggestion)
    reasoning: str = ""
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    cooldown_seconds: float = 60.0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ProactiveNotification(BaseModel):
    """Immutable assistant-level notification model."""

    model_config = ConfigDict(frozen=True)

    notification_id: str = Field(default_factory=lambda: f"notif-{uuid.uuid4().hex[:8]}")
    title: str = ""
    message: str = ""
    notification_type: NotificationType = NotificationType.INFO
    priority: SuggestionPriority = SuggestionPriority.MEDIUM
    read: bool = False
    dismissed: bool = False
    archived: bool = False
    expires_at: Optional[datetime] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ProactiveContext(BaseModel):
    """Immutable snapshot of runtime states supplied to proactive evaluation."""

    model_config = ConfigDict(frozen=True)

    session_id: Optional[str] = None
    user_id: Optional[str] = None
    active_dialogue_state: Optional[str] = None
    last_decision_action: Optional[str] = None
    active_voice_session: bool = False
    idle_time_seconds: float = 0.0
    context_variables: Dict[str, Any] = Field(default_factory=dict)


class ProactiveRule(BaseModel):
    """Immutable rule specification governing proactive behavior triggers."""

    model_config = ConfigDict(frozen=True)

    rule_id: str = Field(default_factory=lambda: f"rule-{uuid.uuid4().hex[:6]}")
    name: str = ""
    description: str = ""
    event_type: str = "*"
    cooldown_seconds: float = 60.0
    min_confidence: float = 0.7
    priority: SuggestionPriority = SuggestionPriority.MEDIUM
    enabled: bool = True
    conditions: Dict[str, Any] = Field(default_factory=dict)


class ProactiveEvaluation(BaseModel):
    """Immutable evaluation report output by the proactive coordinator."""

    model_config = ConfigDict(frozen=True)

    evaluation_id: str = Field(default_factory=lambda: f"eval-{uuid.uuid4().hex[:8]}")
    result: EvaluationResult = EvaluationResult.NO_ACTION
    rule_id: Optional[str] = None
    recommendation: Optional[ProactiveRecommendation] = None
    notification: Optional[ProactiveNotification] = None
    reason: str = "Evaluation complete"
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ProactiveCapabilities(BaseModel):
    """Immutable capabilities specification for the proactive runtime."""

    model_config = ConfigDict(frozen=True)

    supports_proactive_reminders: bool = True
    supports_recommendations: bool = True
    supports_duplicate_suppression: bool = True
    supports_cooldown_tracking: bool = True
    max_active_notifications: int = 100


class ProactiveStatistics(BaseModel):
    """Immutable statistics metrics for proactive evaluation and notifications."""

    model_config = ConfigDict(frozen=True)

    total_evaluations: int = 0
    total_recommendations_generated: int = 0
    total_notifications_created: int = 0
    notifications_dismissed: int = 0
    notifications_archived: int = 0
    duplicates_suppressed: int = 0
    cooldowns_enforced: int = 0
    average_evaluation_latency_ms: float = 0.0
    uptime_seconds: float = 0.0
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ProactiveHealth(BaseModel):
    """Immutable diagnostic health report of the proactive subsystem."""

    model_config = ConfigDict(frozen=True)

    status: str = "READY"
    healthy: bool = True
    subsystems: Dict[str, bool] = Field(default_factory=dict)
    statistics: Dict[str, Any] = Field(default_factory=dict)
    detected_issues: List[str] = Field(default_factory=list)
    checked_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)
